name: Build

on:
  push:
    branches: [master, main]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16.x
      # - name: see directory in electron_dist
      #   run: ls ./electron
      # - name: add key to single keychain
      #   run: security import ./electron/june-ai-single2-certs-electron.p12 -P ${{ secrets.CSC_KEY_PASSWORD }}
      # - name: electron mac os security identities
      #   run: security find-identity -v
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ls
        run: ls ./build

      - name: Retrieve information from package.json
        uses: myrotvorets/info-from-package-json-action@0.0.2
        id: package_json

      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/electron-vite-svelte-${{ steps.package_json.outputs.packageVersion }}.dmg
